name: Run Tests

on:
  push:
    branches: [ main ] # Or specify other branches you want to trigger this on

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Make script executable and run
        run: |
          cd tests
          chmod +x testsuite.sh
          ./testsuite.sh